### ISSUE TITLE
USER STORY 6

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/One-Pico-Restaurant#9]
# User story

As a **user** i want to be able to contact the restaurant for any queries or booking changes as well as navigate easily through the site

## Acceptance criteria:

- 3 columns layout
- Contact details
- Site navigation
- Social links
- Company logo

### Tasks

- [ ] Design footer layout
- [ ] Add all contact details
- [ ] Choose social links
- [ ] Choose icons design
- [ ] Create HTML and CSS code
- [ ] Link social icons to social sites
- [ ] Link the links to site pages
- [ ] Add Copy Right
